import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineComputerDesktop,
  HiOutlineCloud,
  HiOutlineLightBulb,
  HiOutlineDevicePhoneMobile,
} from "react-icons/hi2";

import { FaMicrochip } from "react-icons/fa";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiYoutube,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiReact,
  SiTypescript,
  SiSpringboot,
  SiSpringsecurity,
  SiSpring,
  SiJetpackcompose,
  SiKotlin, SiCplusplus, SiPython,SiDotnet,
  SiMysql,
  SiPostgresql,
  SiGooglegemini,
  SiFirebase,
  SiDocker,
  SiJsonwebtokens,
  SiJson,
  SiHtml5,
  SiBootstrap,
  SiPostman,
  SiAndroidstudio,
} from "react-icons/si";

import { TbApi, TbBrandCSharp, TbShieldCheck, TbFileExcel } from "react-icons/tb";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaJava, FaHtml5, FaCss3, FaMoneyBillTransfer, FaGitAlt,} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  youtube: SiYoutube,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  devices: HiOutlineComputerDesktop,
  cloud: HiOutlineCloud,
  lightbulb: HiOutlineLightBulb,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  react: SiReact,
  typescript: SiTypescript,
  spring: SiSpringboot,
  jetpack: SiJetpackcompose,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  microchip: FaMicrochip,
  java: FaJava,
  kotlin: SiKotlin,
  cpp: SiCplusplus,
  csharp: TbBrandCSharp,
  python: SiPython,
  HTML: FaHtml5,
  html5: SiHtml5,
  CSS: FaCss3,
  css: FaCss3,
  css3: FaCss3,
  bootstrap: SiBootstrap,
  json: SiJson,
  excel: TbFileExcel,
  APS: SiDotnet,
  springsecurity: SiSpringsecurity,
  springjpa: SiSpring,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  firestore: SiFirebase,
  gemini: SiGooglegemini,
  restapi: TbApi,
  payos: FaMoneyBillTransfer,
  docker: SiDocker,
  jwt: SiJsonwebtokens,
  cors: TbShieldCheck,
  postman: SiPostman,
  git: FaGitAlt,
  smartphone: HiOutlineDevicePhoneMobile,
  androidstudio: SiAndroidstudio,
};



export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
